# Generated by Django 3.2.3 on 2021-05-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0004_alter_customer_contect_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contect_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
